### ISSUE TITLE
라운드 선택 [POST] & 참여한 라운드 [GET]

### ISSUE THREAD

**Issue by LeeJeongYeop** [yeniyoo/api_server#14]
사용자가 랜덤한 라운드 중에 YES 나 NO를 선택하는 API
or
자신이 라운드를 YES나 NO로 선택해서 참여한 라운드들의 리스트를 보여주는 API

**Comment by chang12** [comment]
@LeeJeongYeop 
`Pick` 생성하는 API에 Postman로 요청했을때, 아래와 같은 에러가 나는데 확인 부탁드립니다!
round_id 값의 `Round`가 존재하는지 여부는 확인했습니다
![image](https://cloud.githubusercontent.com/assets/12894649/17256001/800f2314-55f6-11e6-9ca0-287f89c3857c.png)

**Comment by chang12** [comment]
@LeeJeongYeop 
#36 PR의 코드에서 (해당 코드를 바로 코멘트로 끌어올 수 있는 방법이 있는지 궁금하네요),
`RoundNicknameManager`의 `next_nickname_id` 메소드의 역할이 궁금합니다.

유저가 라운드를 선택하면서 `RoundNickname`을 입력하는게 아니라, 
수천개 정도의 닉네임 후보군에서 순차적으로 하나씩 배정받는 건가요?

**Comment by chang12** [comment]
@LeeJeongYeop 
어떤 유저가 이미 `Pick`한 `Round`에 대해서 다시 POST method로 `Pick` 생성을 요청했을때 어떻게 처리해야할지도 생각해보면 좋겠네요.
1. 이미 `Pick`한 라운드라며 에러 메시지를 반환
2. 동일한 yes_no 라면 아무 변화 없고, 반대쪽 yes_no 라면 해당 `Pick`에 대한 yes_no를 수정

**Comment by chang12** [comment]
아하!
`round_id_id`, `nickname_id_id` 같은 용법이 있었군요!!!

http://stackoverflow.com/questions/2846029/django-set-foreign-key-using-integer
이 링크보고 정엽님의 깊은 뜻을 이해했습니다.

이 방식을 쓰면 성능면에서 발전이 이뤄지나요?

**Comment by LeeJeongYeop** [comment]
@chang12 
잘못된 네이밍이 개발을 망친다!! ㅠㅠ
