### ISSUE TITLE
Response의 status/message에 대한 논의

### ISSUE THREAD

**Issue by chang12** [yeniyoo/api_server#33]
@LeeJeongYeop 

개발을 진행하다보니, API 응답 body에 status/message를 직접 적어주는것에 대해서 다시한번 논의해보고 싶다는 욕망이 피어올랐습니다! 어제도 정엽님께서 API 설계에 대해 설명해주실때 제가 문의드렸었지요.

API의 로직이 단순한 경우에 (DRF가 제공하는 Generic API View, Serializer 등을 편리하게 활용할 수 있는 경우) DRF가 status와 error message를 알아서 작성해주더라구요. 예를 들어 `/rounds` API에 보낸 요청에 `question`이나 `background_id` 파라미터 중 누락된 값이 있을 경우 알아서 아래처럼 응답을 보내줍니다.

![default](https://cloud.githubusercontent.com/assets/12894649/17163855/0d3e922e-53fe-11e6-86c4-a9303f3d0b41.JPG)

현재 API 규약에서 message에 "round 생성을 위해서는 background_id 파라미터가 필수입니다" 라고 적어주면 더 친절하겠지만, 위 사진 정도의 에러메시지를 보고 이해하는 것도 클라이언트 측의 역할(ㅋㅋㅋ)이 아닌가 생각이 드네요. 

그러고보니 정엽님이 참고한 다른 개발자분들은 왜 응답 body에 status, message를 넣는 방식을 택했을까요?

**Comment by LeeJeongYeop** [comment]
@chang12 
확실히 저런식으로 만들어줘서 보내주면 많이 편하겠네요
일반적으로 status, message의 경우 실제 분기를 나누는거보다 의미적인게 커요.
요청 성공/실패만 담기는게 아니라 요청에 대한 응답이 딱 두가지 경우로 떨어지는 외의 경우도 많거든요
이게 REST 방식만으로 모든걸 표현할 수 없는 것 중 하나 일거라고 생각하는데 그래서 일반적으로 저런식으로 많이 통일해서 보내는 경우가 많아요.
이 부분은 목요일에 만나서 다시 얘기봐요 ㅋㅋ
