### ISSUE TITLE
Comment 모델의 Like 필드

### ISSUE THREAD

**Issue by chang12** [yeniyoo/api_server#39]
@LeeJeongYeop 

현재 코드에서는 `Comment` 모델에서 `like` 필드를 Integer 필드로 따로 가지고 있습니다.
이는 곧 새로운 `CommentLike` 모델 레코드가 생성될때마다 `like` 필드값을 갱신하겠다는 것으로 생각됩니다.

어떤 `Round`를 Pick한 Member 숫자를 받아올때, 이를 `Round`의 필드로 가지고 있지 않고, `model method`로 구현한것 처럼, `Comment`의 `like`값을 받아오는 `model method`를 구현하는 방법도 있을 것 같은데요.

두 가지 방법 각각 장/단점이 있을 듯 하네요.

전자의 장점은 `like`값을 받아올때 오버헤드가 적다는 것이고, 단점은 DB의 정규화를 어기는 것 같은 느낌?
후자의 장/단점은 정확히 반대일 것 같습니다.

정엽님이 설계하실때 전자의 방법을 택하신 이유가 무엇인지 궁금하네요!

**Comment by LeeJeongYeop** [comment]
@chang12 
맞아요 장단점이 확실한데 역시나 잘 파악하셨네요!
데이터베이스에서 count를 동작하는게 해당 테이블을 풀스캔하기 때문에 생각보다 부하가 많이 걸리는 작업이예요.

Round에서 Member를 보여주는 경우는 라운드 하나만 보여주고, Pick에서도 레코드수가 크게 많이질 일이없겠죠. (만약 그렇게 된다면 저희야 좋은 상황이니..ㅋㅋ 그때 튜닝을 해도 괜찮을테고)

하지만 Comment별 like를 보여주는 작업은 댓글과 좋아요 수는 확실히 양에서 차이가 Pick보다 훨씬 많겠죠. 그리고 Comment list 에서 한버에 여러 댓글을 보여줘야하는데 그 댓글마다 count를 돌리면 확실히 꽤나 비용이 많이 드는 작업이 되겠죠.

DB 정규화가 어긋나진 않을꺼예요 단지 개념적으로 봤을땐 불필요한 컬럼하나가 존재하는 것일뿐..
실제로 count를 많이해야되는 경우에서는 저런식으로 구현을 많이하고 그 경우 중 하나가 좋아요나 추천의 경우 입니다.

**Comment by chang12** [comment]
@LeeJeongYeop 
아하! 무슨말씀인지 잘 이해했습니다.

그러면 `CommentLike` 생성 > `Comment`의 `like` 필드 값 갱신 으로 이어지는 일련의 sequence를,
DB에서 atomic한 작업으로 인식하도록 해줘야겠군요?

**Comment by LeeJeongYeop** [comment]
@chang12 
완료완료!!
