### ISSUE TITLE
Comment [POST]로 생성할때 pick_id 파라미터

### ISSUE THREAD

**Issue by chang12** [yeniyoo/api_server#41]
@LeeJeongYeop 
구글 드라이브의 API 문서를 보면,
`/rounds/{round_id}/comments' URI에 POST method로 새로운`Comment`를 생성하는 API에서,
`pick_id` 파라미터를 클라이언트가 요청에 담아줘야 합니다.

`Pick` 릴레이션의 PK가 `user_id`, `round_id`로 구성되어있는데요.
`Authentication` > `user_id`
`URI` >`round_id` 로 서버에서 값을 얻어올 수 있으므로,
`pick_id` 파라미터를 굳이 받을 필요가 없을 것 같습니다.

정엽님은 어떻게 생각하세요?

**Comment by chang12** [comment]
API 문서를 잘못 읽고, 쓸데 없는 의문을 가진 상황이었음....

**Comment by LeeJeongYeop** [comment]
요런일이!
