### ISSUE TITLE
Comment, Recomment에서 닉네임을 안주고 있네요.

### ISSUE THREAD

**Issue by LeeJeongYeop** [yeniyoo/api_server#47]
댓글이나, 대댓글을 누가썼다는 nickanme을 보여줘야 할거같아요.

get_queryset(self) 여기 오버라이딩 한 부분에서 해보려고 했는데 실패했습니다. ㅠㅠ

**Comment by chang12** [comment]
아아....!!
생각치못했던 중요한 이슈네요.

우선 구글드라이브의 `API 명세`를 수정했습니다.
Comment, Recomment에서 GET method에 반환해줄때, `"user_id"`라는 이름의 필드를 추가해줘야겠군요.

**Comment by LeeJeongYeop** [comment]
user_id보단 nickname을 직접적으로 줘야할거같아요.
user_id를 통해서 상대의 정보를 보거나 하진않고, 단순히 익명의 닉네임을 표시해줄뿐이니,..

**Comment by chang12** [comment]
아아............!!!!!!!!!

구현한줄 알았는데, 어떻게 구현했는지 코멘트 달려고 돌아왔더니,
제가 또 잘못 읽었네요 ㅋㅋㅋㅋㅋ

**Comment by chang12** [comment]
@LeeJeongYeop 
이 이슈랑 별개의 주제긴 하지만, 이 이슈 해결을 위한 고민에서 파생된 질문입니다.

현재 `RoundNickname` model에 `user_id`, `round_id` field가 있는데요.
이를 `pick_id` 하나로 나타내지 않은 이유가 궁금하네요.
