### ISSUE TITLE
Model 정의할때 참조 관계 Field 네이밍에 대하여

### ISSUE THREAD

**Issue by chang12** [yeniyoo/api_server#48]
@LeeJeongYeop 
저희 API 서버의 Schema에서 참 많은 참조관계가 존재하죠.
`Round` -> `User`
`Comment` -> `Round`
등등....

현재 Schema에서는 참조하는 쪽에서 참조받는 쪽을 가리키는 필드 이름을 지을때, 
`참조받는 모델명_id` 형태로 붙이고 있습니다.
실제 Django ORM에 의해서 만들어진 DB 테이블에서, 
컬럼 이름을 붙일때 같은 방식을 사용하므로 자연스럽습니다.

그러나 한편으로 Django ORM을 사용해서 새로운 레코드를 생성하는 `objects.create()` 메소드에서는
ForeignKey 필드의 값을 입력받을때 id 값을 허용하지 않고, 참조받는 모델의 인스턴스를 요구합니다.
그래서 `create(round_id=round_인스턴스)` 같은 형태가 되어 코드가 개인적으로 헷갈리게 되네요.

https://docs.djangoproject.com/en/1.9/ref/models/fields/#foreignkey
Django 공식 문서를 보면, 참조하는쪽에서 필드 이름을 붙일때, 
참조받는 모델의 이름을 그대로 사용함을 볼 수 있습니다.

그래서 저희도 `참조받는 모델명`으로 네이밍하면 어떨까 싶네요.
논의해보면 좋겠습니다!

**Comment by LeeJeongYeop** [comment]
네 저도 django에서 fk에 대해 _id를 저절로 붙여지는걸 잊고 그렇게 만들었었는데 수정할 수 있을때 얼른 수정하는게 좋을거같아요

**Comment by chang12** [comment]
@LeeJeongYeop 
아 넵! 그러면 이 issue 번호 브랜치로 해당작업 진행해보겠습니다.
