### ISSUE TITLE
#47 구현 개선방안

### ISSUE THREAD

**Issue by chang12** [yeniyoo/api_server#50]
현재: `Comment Serializer`에서 nickname 받아오는 로직을 담당
제안: `Comment`의 `model method`에서 해당 로직을 담당

필요조건: `RoundNickname` 모델의 schema 변경
- `user_id`,`round_id` Foreign key -> `pick_id` OneToOneField

추후 보완하면 좋을 듯!

**Comment by LeeJeongYeop** [comment]
넵! round에 대한 개인 정보는 pick에서 관리하니 저렇게 연결되는데 오히려 자연스럽겠네요!

**Comment by chang12** [comment]
@LeeJeongYeop 
issue를 구현하던 중에 문득....
`Pick` model에 추가로 `RoundNickname` model이 필요한 이유에 대해 의문이 들더군요.

현재 `RoundNickname`의 역할은 `Pick`과 `Nickname`을 연계해주는 것인데요.
`Pick`에서 바로 `Nickname`와 관계를 맺어도 로직에 문제가 없을 것 같다는 생각입니다.

정엽님께서는 어떻게 생각하시나요?

**Comment by LeeJeongYeop** [comment]
@chang12 
오 그래네요! RoundNickname을 먼저 생각하고 Pick을 구상했던 부분이라 제가 놓쳤던거같네요
말씀하신데로 모델 수정하면 좋을거같아요!
