### ISSUE TITLE
Comment, Recomment Like 추가 삭제시 트랜잭션 처리

### ISSUE THREAD

**Issue by LeeJeongYeop** [yeniyoo/api_server#54]
지금 구현된 내용은 Comment에 like 수가 오르거나 내려가지 않고 있는데 이 부분도 같이 구현해야될거같아요!
그리고 이거 말씀을 못드린거같은데 저희 기획에서 Comment, Recomment like 할때 유저가 yes를 Pick했으면 yes의 Comment, Recomment만 like 하도록 하기로 해서 이 부분도 막아줘야할거같아요!

**Comment by chang12** [comment]
아하! 중요한 부분이네요. 확인했습니다.

**Comment by chang12** [comment]
`CommentLike` 생성 > `Comment`의 like +1
`CommentLike` 삭제 > `Comment`의 like -1

이 로직을 어느단에서 구현하는게 **"적절"**할지 궁금해지네요.

1) Serializer와 View에 로직을 삽입 (윗단을 건드리는 방법)
2) 커스텀 Model Manager를 정의하여 `create`, `delete` 메소드를 오버라이딩 (아랫단을 건드리는 방법)

**Comment by chang12** [comment]
음... 공식 문서들을 읽다보니 1)의 방식이 낫겠다는 생각이 드네요.
`transaction`을 잘 묶어주는것만 신경써주면 되겠습니다.

**Comment by chang12** [comment]
Django `Signal`을 사용하면 더 좋겠지만, 우선은 저희 프로젝트에서는 `CommentLike` 모델 관련 CRUD 작업이 모두 `CommentLikeSerializer`에 의해서만 이뤄지니 해당 부분에만 코드를 삽입해도 될 듯 합니다.

**Comment by LeeJeongYeop** [comment]
@chang12 넵 나중에 signal로 바꾸던지 해도 괜찮겠네요!
