### ISSUE TITLE
Comment Yes_No 구분

### ISSUE THREAD

**Issue by LeeJeongYeop** [yeniyoo/api_server#55]
아 이거 까먹고 있었네요;;;ㅋㅋ
Comment
Get하고 Post나눠야 할꺼같아요
GET: /rounds/{round}/comments/{yes_no}
POST: /rounds/{round}/comments/

더 좋은 방식 생각나시면 말씀해주세요. 결정나면 수정하죠!

**Comment by chang12** [comment]
아아아! 저도 깜빡하고있었습니다.... ㅋㅋㅋㅋ

yes_no값을 GET URI에서 패턴에 포함시켜받지않고,
GET parameter 로 받아오면 어떨까요?

**Comment by LeeJeongYeop** [comment]
그것도 좋겠네요! 기존을 유지시킬수도 있고! 좋습니당!

**Comment by chang12** [comment]
#56 PR에서 해소했습니다.
