### ISSUE TITLE
/likes -> /comments/{comment_id}/likes ??

### ISSUE THREAD

**Issue by chang12** [yeniyoo/api_server#57]
@LeeJeongYeop 
지난번 강남역에서 둘이 만나서 논의할때 분명 얘기했음직한데....

`/comments/{comment_id}/likes` 대신에
`/likes`로 URI를 설계한 이유가 무엇이었죠?

**Comment by LeeJeongYeop** [comment]
@chang12 
헐... ㅋㅋ 기억이 잘 안나네요...
`/comments/{comment_id}/likes`
이 방식으로 해도 괜찮을거 같아보이네요

**Comment by chang12** [comment]
@LeeJeongYeop 
이에 대해 생각하다보니, 또 재밌어지네요.

만약 `/comments/{comment_id}/likes`로 `CommentLike`를 생성한다고 하면, `POST` method의 요청이지만 body에 아무것도 넣을 필요가 없습니다. `user` field는 `request` context에서, `comment` field는 `URI parameter`에서 알 수 있으니까요.

그러니 body 없는 POST 요청이 된다는게 재밌네요.

**Comment by chang12** [comment]
@LeeJeongYeop 
작업 들어가겠습니다.

**Comment by chang12** [comment]
`CommentLike` 인스턴스가 하나 생성될때마다 연관된 `Comment` 인스턴스의 `like` 필드값을 1 키우는 연산을 더 효율적으로 수행하기 위해서, "**F expression**"을 쓰는 방식이 추천되고 있네요.

https://docs.djangoproject.com/en/1.10/ref/models/expressions/#django.db.models.F

**Comment by LeeJeongYeop** [comment]
@chang12 
와 F expression 요거 지원해주는게 신기하네요

**Comment by chang12** [comment]
## 에러 처리
- [x] 존재하지 않는 `Comment`에 대한 요청 > `CommentLikeSerializer` 단의 로직을 수정
- [x] `Pick`하지 않은 `User`의 요청 > 'CommentLikeSerializer` 단의 로직을 수정
- [x] 'Pick'은 있지만, 반대편 진영을 택한 `User`의 요청 > `CommentLikeSerializer` 단으 로직을 수정
- [x] `POST` 요청 후 재요청 > `CommentLikeSerializer` 단의 로직을 수정
- [x] `DELETE` 요청 후 재요청 > `delete` 메소드에 이미 내장되어 있음.

**Comment by chang12** [comment]
위의 1,2번 항목에 대한 로직을,
- `permissions`을 커스터마이징 해서 추가할지,
- `post`/`delete` 메소드 오버라이딩 하는 부분에 추가할지,

고민 중....

**Comment by LeeJeongYeop** [comment]
저 두가지 선택 외에 로직 자체에서 막아주는 방법도 괜찮을거 같아요

**Comment by chang12** [comment]
@LeeJeongYeop 로직 자체에서 막아주는 방법은 어떤건가요?
