### ISSUE TITLE
POST /rounds/{round_id}/comments 에서 Pick 안한 유저의 시도 에러처리

### ISSUE THREAD

**Issue by chang12** [yeniyoo/api_server#60]

**Comment by chang12** [comment]
작업 돌입했습니다.

**Comment by chang12** [comment]
@LeeJeongYeop 
YES랑 NO 중에서 자신이 선택한 진영에만 댓글을 쓸 수 있는건가요?

**Comment by chang12** [comment]
- `ObjectDoesNotExist` exception에 대한 에러처리 로직을 추가

**Comment by LeeJeongYeop** [comment]
@chang12 
넵 자신의 진영에만 댓글쓰고 자신의 진영쪽에서 쓴 글에만 좋아요 누를수있어요

**Comment by chang12** [comment]
`Comment`를 생성할 때, 유저 정보 + `Round` 정보로부터 `Pick` 정보를 뽑아내서 pick 필드값을 채우므로 굳이 `yes_no` 값을 명시할 필요는 없겠군요!
