### ISSUE TITLE
POST /picks 에러처리(해당 user,round 조합에 pick이 존재하는 경우)

### ISSUE THREAD

**Issue by chang12** [yeniyoo/api_server#61]
- **"이미 선택한 라운드입니다."** 라며 에러 출력.
- `yes_no` 필드의 값을 업데이트

**Comment by chang12** [comment]
앱에서 정상적인 UX 진행을 따른다면, 이미 `Pick`한 라운드에 다시 `Pick`할 경우가 없으려나?

**Comment by LeeJeongYeop** [comment]
@chang12 
Pick을 재선택하는 부분은 얘기가 나왔었는데 안정해졌었어요

**Comment by chang12** [comment]
@LeeJeongYeop 
클라이어트단이 잘 구현되었다면, 불가능한 동작이니 에러처리하는 것으로 진행하겠습니다.

**Comment by chang12** [comment]
## Empty QuerySet에 대한 Assert

http://stackoverflow.com/questions/1387727/checking-for-empty-queryset-in-django

**Comment by chang12** [comment]
`pick` view 단에 로직을 추가해서 에러를 처리하도록 구현함.
