### ISSUE TITLE
GET /rounds 에서 

### ISSUE THREAD

**Issue by chang12** [yeniyoo/api_server#65]
`디자이너`분들이 올려주신 스크린 이미지들을 보니, `Round` 하나를 띄워주는 스크린에서 해당 `Round`를 선택한 `멤버 숫자` 뿐 아니라 `댓글 개수`도 보여주네요.

API도 그에 맞춰 수정해주면 좋을 듯 합니다.

**Comment by LeeJeongYeop** [comment]
@chang12 
그렇군요 댓글 수는 카운트 해도 별 무리없어보이네요!

**Comment by chang12** [comment]
작업 시작해놓고, 코멘트를 안 달았네요.
